name: 翻译反馈
description: 游戏文本漏翻或者翻译建议
labels: ['翻译反馈']
body:
  - type: textarea
    id: describe
    attributes:
      label: 描述你的问题
      description: 简要描述你的问题
      value: |
        比如：
        我在xxx发现有漏翻，内容是xxx。
        我建议把xxx换成xxx。
    validations:
      required: true
  - type: textarea
    id: describe2
    attributes:
      label: 你的建议说明
      description: 比如：游戏里Suzume的角色形象出自《战国兰斯》里的すずめ，并且官方翻译是铃女
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: 截图
      description: |
        如果有，添加屏幕截图以帮助解释你的问题。
        提示: 可以通过点击这个区域，然后把文件拖进来添加图片或日志文件。
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: 还有别的吗？
      description: |
        比如说对说明补充或者修改建议等等。
    validations:
      required: false
